#!/bin/bash

# Local AI Suite - Global CLI Installation Script
# Makes 'ai' command available globally from anywhere

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get script directory (where Local AI Suite is installed)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AI_SCRIPT="$SCRIPT_DIR/scripts/ai.py"

echo -e "${YELLOW}Local AI Suite - Global CLI Installation${NC}"
echo "Installing from: $SCRIPT_DIR"

# Check if ai.py exists
if [[ ! -f "$AI_SCRIPT" ]]; then
    echo -e "${RED}Error: ai.py not found at $AI_SCRIPT${NC}"
    exit 1
fi

# Check if Python 3 is available
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: Python 3 is required but not installed${NC}"
    exit 1
fi

# Create user local bin directory if it doesn't exist
mkdir -p "$HOME/.local/bin"

# Create global wrapper script
GLOBAL_SCRIPT="$HOME/.local/bin/ai"
echo "Creating global 'ai' command at $GLOBAL_SCRIPT"

# Create the wrapper script
tee "$GLOBAL_SCRIPT" > /dev/null << EOF
#!/bin/bash
# Local AI Suite Global CLI Wrapper
# Automatically generated by install.sh

# Change to the Local AI Suite directory
cd "$SCRIPT_DIR"

# Execute the AI CLI with all arguments
exec python3 "$AI_SCRIPT" "\$@"
EOF

# Make it executable
chmod +x "$GLOBAL_SCRIPT"

echo -e "${GREEN}✓ Global 'ai' command installed successfully!${NC}"
echo ""
echo -e "${YELLOW}IMPORTANT: Add ~/.local/bin to your PATH if not already added:${NC}"
echo "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
echo "  source ~/.bashrc"
echo ""
echo "Usage examples:"
echo "  ai \"Hello world\""
echo "  ai --code \"Create a Python function\""
echo "  ai --interactive"
echo ""
echo "You can now use 'ai' command from any directory!"

# Test the installation
echo "Testing installation..."
if command -v ai &> /dev/null; then
    echo -e "${GREEN}✓ Installation test passed${NC}"
else
    echo -e "${RED}✗ Installation test failed${NC}"
    exit 1
fi