[tool.black]
line-length = 100
target-version = ['py311']

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
# Ignore specific rules that are too strict or not applicable
ignore = [
    "E722",  # Bare except (intentional in some error handling)
    "F401",  # Unused imports (some are for try/except availability checks)
    "F821",  # Undefined name (some imports are conditional)
    "F841",  # Unused local variable (some are placeholders)
    "E712",  # Comparison to True/False (explicit for clarity in tests)
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports are OK in __init__.py
"tests/**/*.py" = ["E712", "F841"]  # Test files can be more lenient
