server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # AI Suite service logs from files
  - job_name: ai-services
    static_configs:
      - targets:
          - localhost
        labels:
          job: ai-services
          __path__: /var/log/ai-services/*.log

  # Docker container logs
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '^/(.*)$'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'

  # Specific service log parsing
  - job_name: api-gateway
    static_configs:
      - targets:
          - localhost
        labels:
          job: api-gateway
          service: api-gateway
          __path__: /var/log/ai-services/api-gateway.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            request_id: request_id
            endpoint: endpoint
            method: method
            status_code: status_code
            duration_ms: duration_ms
      - labels:
          level:
          request_id:
          endpoint:
          method:
          status_code:

  - job_name: rag-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: rag-service
          service: rag
          __path__: /var/log/ai-services/rag.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            request_id: request_id
      - labels:
          level:
          request_id:

  - job_name: mcp-server
    static_configs:
      - targets:
          - localhost
        labels:
          job: mcp-server
          service: mcp-server
          __path__: /var/log/ai-services/mcp-server.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            request_id: request_id
            tool_name: tool_name
            session_id: session_id
      - labels:
          level:
          request_id:
          tool_name:
          session_id: