version: "3.9"

services:
  inference:
    env_file: ../.env
    image: ghcr.io/ggerganov/llama.cpp:server
    command: [
      "--host", "0.0.0.0",
      "--port", "8001",
      "--model", "/models/${CHAT_MODEL}",
      "--parallel", "4",
      "--ctx-size", "8192",
      "--n-gpu-layers", "35",
      "--timeout", "600"
    ]
    volumes:
      - /mnt/e/ai-models:/models:ro
    ports:
      - "${INFERENCE_PORT:-8001}:8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    restart: unless-stopped

  api-gateway:
    env_file: ../.env
    image: ghcr.io/berriai/litellm:main-latest
    command: ["--config", "/app/config.yaml", "--port", "8000", "--host", "0.0.0.0"]
    environment:
      - LITELLM_CONFIG=/app/config.yaml
      - LITELLM_LOG=INFO
    volumes:
      - ../services/api-gateway/config.p1.yaml:/app/config.yaml:ro
    ports:
      - "${API_GATEWAY_PORT:-8000}:8000"
    depends_on:
      inference:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  default:
    driver: bridge