version: "3.9"

services:
  # Phase 1 services (inference + api-gateway)
  inference:
    env_file: ../.env
    image: ghcr.io/ggerganov/llama.cpp:server
    command: [
      "--host", "0.0.0.0",
      "--port", "8001",
      "--model", "/models/qwen2.5-14b-instruct-q4_k_m.gguf",
      "--parallel", "4",
      "--ctx-size", "8192",
      "--n-gpu-layers", "35",
      "--timeout", "600"
    ]
    volumes:
      - ../models:/models:ro
    ports:
      - "${INFERENCE_PORT:-8001}:8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    restart: unless-stopped

  api-gateway:
    env_file: ../.env
    image: ghcr.io/berriai/litellm:main-latest
    command: ["--config", "/app/config.yaml", "--port", "8000", "--host", "0.0.0.0"]
    environment:
      - LITELLM_CONFIG=/app/config.yaml
      - LITELLM_LOG=INFO
    volumes:
      - ../services/api-gateway/config.p1.yaml:/app/config.yaml:ro
    ports:
      - "${API_GATEWAY_PORT:-8000}:8000"
    depends_on:
      inference:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Phase 2 services (RAG components)
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      disable: true
    restart: unless-stopped

  embedding:
    build:
      context: ../services/embedding
      dockerfile: Dockerfile
    ports:
      - "${EMBEDDING_PORT:-8003}:8003"
    volumes:
      - embedding_models:/app/models
    environment:
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-BAAI/bge-small-en-v1.5}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    restart: unless-stopped

  rag-service:
    build:
      context: ../services/rag
      dockerfile: Dockerfile
    ports:
      - "${RAG_PORT:-8002}:8002"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_URL=http://embedding:8003
      - LLM_URL=http://api-gateway:8000/v1
      - LLM_MODEL=qwen2.5-14b-instruct
    volumes:
      - ../documents:/app/documents:ro
    depends_on:
      qdrant:
        condition: service_healthy
      embedding:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  qdrant_data:
  embedding_models:

networks:
  default:
    driver: bridge