services:
  # Mock Chat 모델 서버 (CPU 전용 CI용)
  inference-chat:
    build:
      context: ../services/mock-inference
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: ["${INFERENCE_PORT:-8001}:8001"]
    environment:
      - MODEL_NAME=chat-7b
      - PORT=8001
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Mock Code 모델 서버 (CPU 전용 CI용)
  inference-code:
    build:
      context: ../services/mock-inference
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: ["8004:8001"]
    environment:
      - MODEL_NAME=code-7b
      - PORT=8001
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  api-gateway:
    image: ghcr.io/berriai/litellm:main-latest
    restart: unless-stopped
    ports: ["${API_GATEWAY_PORT:-8000}:8000"]
    volumes:
      - ../services/api-gateway/config.p2.yaml:/app/config.yaml:ro
    platform: linux/amd64
    command: ["--config", "/app/config.yaml", "--port", "8000", "--host", "0.0.0.0"]
    environment:
      - LITELLM_LOG=warning
      - TIMEOUT=${LLM_REQUEST_TIMEOUT:-60}
    depends_on:
      inference-chat:
        condition: service_healthy
      inference-code:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s

  rag:
    build:
      context: ../services/rag
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: ["${RAG_PORT:-8002}:8002"]
    volumes:
      # CI에서는 빈 디렉토리 사용
      - rag-documents:/app/documents:ro
    environment:
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - EMBEDDING_URL=${EMBEDDING_URL:-http://embedding:8003}
      - API_GATEWAY_URL=${API_GATEWAY_URL:-http://api-gateway:8000}
      - RAG_LLM_TIMEOUT=${RAG_LLM_TIMEOUT:-120}
      - RAG_LLM_MAX_TOKENS=${RAG_LLM_MAX_TOKENS:-256}
      - RAG_LLM_TEMPERATURE=${RAG_LLM_TEMPERATURE:-0.3}
      - RAG_TOPK=${RAG_TOPK:-4}
      - RAG_CHUNK_SIZE=${RAG_CHUNK_SIZE:-512}
      - RAG_CHUNK_OVERLAP=${RAG_CHUNK_OVERLAP:-100}
      - API_GATEWAY_CHAT_MODEL=${API_GATEWAY_CHAT_MODEL:-chat-7b}
      - API_GATEWAY_CODE_MODEL=${API_GATEWAY_CODE_MODEL:-code-7b}
      - QDRANT_MAX_RETRIES=${QDRANT_MAX_RETRIES:-3}
      - QDRANT_RETRY_MIN_WAIT=${QDRANT_RETRY_MIN_WAIT:-2}
      - QDRANT_RETRY_MAX_WAIT=${QDRANT_RETRY_MAX_WAIT:-10}
      - QDRANT_TIMEOUT=${QDRANT_TIMEOUT:-30}
      - EMBEDDING_TIMEOUT=${EMBEDDING_TIMEOUT:-30}
    depends_on:
      qdrant:
        condition: service_healthy
      embedding:
        condition: service_healthy
      api-gateway:
        condition: service_healthy

  embedding:
    build:
      context: ../services/embedding
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: ["${EMBEDDING_PORT:-8003}:8003"]
    environment:
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-BAAI/bge-small-en-v1.5}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8003/health')"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      # CI에서는 임시 볼륨 사용
      - qdrant-storage:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "grep -q ':18BD' /proc/net/tcp || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  rag-documents:
  qdrant-storage:
