groups:
  - name: ai_suite_alerts
    rules:
      # High-level service availability
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute."

      # API Gateway specific alerts
      - alert: APIGatewayHighErrorRate
        expr: rate(http_requests_total{job="api-gateway",status_code=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on API Gateway"
          description: "API Gateway error rate is {{ $value }} errors/sec over the last 5 minutes"

      - alert: APIGatewayHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="api-gateway"}[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High latency on API Gateway"
          description: "API Gateway 95th percentile latency is {{ $value }}s"

      # RAG Service alerts
      - alert: RAGServiceVectorSearchFailing
        expr: vector_search_errors_total > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Vector search errors detected"
          description: "RAG service has {{ $value }} vector search errors"

      # Memory and resource alerts
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 85% (current: {{ $value }}%)"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% (current: {{ $value }}%)"

      # Container resource alerts
      - alert: ContainerHighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 90
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Container high memory usage"
          description: "Container {{ $labels.name }} memory usage is {{ $value }}%"

      - alert: ContainerHighCPUUsage
        expr: (rate(container_cpu_usage_seconds_total[5m]) * 100) > 80
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Container high CPU usage"
          description: "Container {{ $labels.name }} CPU usage is {{ $value }}%"