global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # AI Suite Services
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  - job_name: 'rag-service'
    static_configs:
      - targets: ['rag:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  - job_name: 'embedding-service'
    static_configs:
      - targets: ['embedding:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:8020']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Infrastructure Services
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: '/metrics'
    params:
      collect[]: ['info']