global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@ai-suite.local'
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-receiver'
      group_wait: 10s
      repeat_interval: 5m

receivers:
  - name: 'default-receiver'
    # Webhook disabled - no alert endpoint configured
    # To enable: add webhook_configs with valid endpoint

  - name: 'critical-receiver'
    # Webhook disabled - no alert endpoint configured
    # To enable: add webhook_configs with valid endpoint

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']