  name: CI Pipeline

  on:
    push:
      branches: [ main, develop, issue-* ]
    pull_request:
      branches: [ main, develop ]
    schedule:
      - cron: '0 2 * * *'  # Nightly at 2am UTC
    workflow_dispatch:
      inputs:
        run_load_tests:
          description: 'Run load tests'
          required: false
          default: 'false'

  jobs:
    lint:
      name: Lint & Format Check
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'

        - name: Install linting tools
          run: |
            pip install black ruff

        - name: Black format check
          run: |
            black --check services/ scripts/ || {
              echo "::error::Code formatting issues found. Run 'black services/ scripts/' to fix."
              exit 1
            }

        - name: Ruff lint
          run: |
            ruff check services/ scripts/ || {
              echo "::error::Linting issues found. Run 'ruff check --fix services/ scripts/' to fix."
              exit 1
            }

    security-scan:
      name: Security Scan
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install security scan tools
          run: |
            pip install bandit safety

        - name: Bandit security scan
          run: |
            bandit -r services/ -f json -o bandit-report.json || true
            bandit -r services/ -ll || echo "::warning::Bandit found potential security issues"

        - name: Safety dependency check
          run: |
            # Collect all requirements files
            find services -name "requirements.txt" -exec cat {} \; > all-requirements.txt
            safety check --file all-requirements.txt --json || echo "::warning::Safety found vulnerable dependencies"

        - name: Upload security reports
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: security-reports
            path: |
              bandit-report.json
              all-requirements.txt
            retention-days: 30

    unit-tests:
      name: Unit Tests (${{ matrix.service }})
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          service: [mcp-server, rag, embedding]

      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'

        - name: Install test dependencies
          run: |
            pip install pytest pytest-cov pytest-asyncio httpx

            # Install service-specific dependencies
            if [ -f services/${{ matrix.service }}/requirements.txt ]; then
              pip install -r services/${{ matrix.service }}/requirements.txt
            fi

        - name: Run tests with coverage
          working-directory: services/${{ matrix.service }}
          run: |
            # Skip tests if no test directory exists
            if [ ! -d "tests" ]; then
              echo "::warning::No tests directory found for ${{ matrix.service }}"
              exit 0
            fi

            pytest tests/ \
              --cov=. \
              --cov-report=xml \
              --cov-report=term-missing \
              --cov-report=html \
              -v || exit 1

        - name: Upload coverage to Codecov
          if: always()
          uses: codecov/codecov-action@v4
          with:
            files: ./services/${{ matrix.service }}/coverage.xml
            flags: ${{ matrix.service }}
            name: ${{ matrix.service }}-coverage
            fail_ci_if_error: false

        - name: Upload coverage HTML report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: coverage-${{ matrix.service }}
            path: services/${{ matrix.service }}/htmlcov/
            retention-days: 30

    # Integration tests with CPU profile (Mock LLM servers)
    integration-tests:
      name: Integration Tests (CPU Profile)
      runs-on: ubuntu-latest
      needs: [unit-tests]

      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install test dependencies
          run: |
            pip install pytest pytest-asyncio httpx

        - name: Start services with CPU profile
          run: |
            docker compose -f docker/compose.p2.cpu.yml up -d
            echo "::notice::Services starting with Mock LLM servers (CPU-only)"

        - name: Wait for services
          run: |
            echo "Waiting 60 seconds for all services to be ready..."
            sleep 60

        - name: Health checks
          run: |
            echo "::group::Service Health Checks"

            # Check inference servers (mock)
            curl -f http://localhost:8001/health || echo "::warning::Inference Chat health check failed"
            curl -f http://localhost:8004/health || echo "::warning::Inference Code health check failed"

            # Check API Gateway
            curl -f http://localhost:8000/health || curl -f http://localhost:8000/v1/models || echo "::warning::API Gateway health check failed"

            # Check RAG
            curl -f http://localhost:8002/health || echo "::warning::RAG health check failed"

            # Check Embedding
            curl -f http://localhost:8003/health || echo "::warning::Embedding health check failed"

            echo "::endgroup::"

        - name: Run basic integration tests
          run: |
            echo "::group::Integration Tests"
            # These tests verify service connectivity, not actual inference
            pytest tests/integration/test_api_gateway.py::test_api_gateway_health -v || echo "::warning::Health test failed"
            echo "::endgroup::"

        - name: Run RAG integration tests
          run: |
            echo "::group::RAG Integration Tests"
            # Run RAG service end-to-end tests (requires Phase 2 stack)
            make test-rag-integration-coverage || echo "::warning::RAG integration tests failed"
            echo "::endgroup::"
  
        - name: Upload RAG integration coverage
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: rag-integration-coverage
            path: docs/rag_integration_coverage.json
            retention-days: 30

        - name: Show service logs on failure
          if: failure()
          run: |
            echo "::group::Service Logs"
            docker compose -f docker/compose.p2.cpu.yml logs
            echo "::endgroup::"

        - name: Teardown
          if: always()
          run: |
            docker compose -f docker/compose.p2.cpu.yml down -v

    # Phase 1: RAG Integration Tests
    rag-integration-tests:
      name: RAG Integration Tests (Phase 1)
      runs-on: ubuntu-latest
      needs: [lint, unit-tests]
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'

        - name: Install test dependencies
          run: |
            pip install pytest pytest-asyncio pytest-cov httpx

        - name: Install service dependencies
          run: |
            if [ -f services/rag/requirements.txt ]; then
              pip install -r services/rag/requirements.txt
            fi

        - name: Start services with CPU profile
          run: |
            docker compose -f docker/compose.p2.cpu.yml up -d
            echo "::notice::Starting Phase 2 stack for RAG integration tests"

        - name: Wait for services
          run: |
            echo "Waiting 60 seconds for all services to be ready..."
            sleep 60

        - name: Health checks
          run: |
            echo "::group::RAG Service Health Checks"
            curl -f http://localhost:8000/v1/models || echo "::warning::API Gateway health check failed"
            curl -f http://localhost:8002/health || echo "::warning::RAG service health check failed"
            curl -f http://localhost:8003/health || echo "::warning::Embedding service health check failed"
            echo "::endgroup::"

        - name: Run RAG integration tests (Phase 1)
          run: |
            echo "::group::RAG Integration Tests - Phase 1"
            make test-rag-integration-extended
            echo "::endgroup::"

        - name: Upload coverage reports
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: rag-integration-phase1-coverage
            path: docs/rag_extended_coverage.json
            retention-days: 30

        - name: Show logs on failure
          if: failure()
          run: |
            echo "::group::Service Logs"
            docker compose -f docker/compose.p2.cpu.yml logs
            echo "::endgroup::"

        - name: Teardown
          if: always()
          run: |
            docker compose -f docker/compose.p2.cpu.yml down -v

    # Phase 2: E2E Playwright Tests
    e2e-tests:
      name: E2E Tests - Desktop App (Phase 2)
      runs-on: ubuntu-latest
      needs: [lint]
      strategy:
        fail-fast: false
        matrix:
          browser: [chromium, firefox, webkit]

      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: 'npm'
            cache-dependency-path: desktop-app/package-lock.json

        - name: Install desktop app dependencies
          working-directory: desktop-app
          run: |
            npm install

        - name: Install Playwright browsers
          working-directory: desktop-app
          run: |
            npx playwright install ${{ matrix.browser }}

        - name: Start backend services with CPU profile
          run: |
            docker compose -f docker/compose.p2.cpu.yml up -d
            echo "::notice::Starting Phase 2 stack for E2E tests"

        - name: Wait for backend services to be ready
          run: |
            echo "Waiting 60 seconds for all services to be ready..."
            sleep 60

        - name: Health check backend services
          run: |
            echo "::group::Backend Service Health Checks"
            curl -f http://localhost:8000/v1/models || echo "::warning::API Gateway health check failed"
            curl -f http://localhost:8002/health || echo "::warning::RAG service health check failed"
            curl -f http://localhost:8003/health || echo "::warning::Embedding service health check failed"
            echo "::endgroup::"

        - name: Run E2E tests
          working-directory: desktop-app
          run: |
            echo "::group::E2E Tests - ${{ matrix.browser }} browser"
            npm run test:e2e -- --project=${{ matrix.browser }} || {
              echo "::warning::E2E tests failed for ${{ matrix.browser }}"
              exit 1
            }
            echo "::endgroup::"

        - name: Upload Playwright report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: playwright-report-${{ matrix.browser }}
            path: desktop-app/playwright-report/
            retention-days: 30

        - name: Show backend service logs on failure
          if: failure()
          run: |
            echo "::group::Backend Service Logs"
            docker compose -f docker/compose.p2.cpu.yml logs
            echo "::endgroup::"

        - name: Teardown backend services
          if: always()
          run: |
            docker compose -f docker/compose.p2.cpu.yml down -v

    # Phase 3: Load Tests (Nightly only)
    load-tests:
      name: Load Tests (Phase 3)
      runs-on: ubuntu-latest
      if: github.event_name == 'schedule' || github.event.inputs.run_load_tests == 'true'
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'

        - name: Install Locust and dependencies
          run: |
            pip install locust fasthttp

        - name: Start services with CPU profile
          run: |
            docker compose -f docker/compose.p2.cpu.yml up -d
            echo "::notice::Starting Phase 2 stack for load testing"

        - name: Wait for services
          run: |
            echo "Waiting 60 seconds for all services to be ready..."
            sleep 60

        - name: Run baseline test
          run: |
            echo "::group::Load Test - Baseline (1 user, 2 min)"
            make test-load-baseline || echo "::warning::Baseline test failed"
            echo "::endgroup::"

        - name: Run API Gateway load tests
          run: |
            echo "::group::Load Test - API Gateway (10→50→100 users, 15 min)"
            make test-load-api || echo "::warning::API Gateway load test failed"
            echo "::endgroup::"

        - name: Run RAG Service load tests
          run: |
            echo "::group::Load Test - RAG Service (5→25→50 users, 15 min)"
            make test-load-rag || echo "::warning::RAG Service load test failed"
            echo "::endgroup::"

        - name: Run MCP Server load tests
          run: |
            echo "::group::Load Test - MCP Server (5→20 users, 10 min)"
            make test-load-mcp || echo "::warning::MCP Server load test failed"
            echo "::endgroup::"

        - name: Extract metrics from load test results
          if: always()
          run: |
            echo "::group::Performance Metrics Extraction"
            python3 scripts/extract_metrics.py load_results_stats.csv load-results.json || echo "::warning::Metric extraction failed"
            echo "::endgroup::"

        - name: Compare against performance baseline
          if: always()
          run: |
            echo "::group::Performance Regression Detection"
            python3 scripts/compare_performance.py docs/performance-baselines.json load-results.json || echo "::notice::Performance regressions detected - see report"
            echo "::endgroup::"

        - name: Create GitHub issue for regressions
          if: always() && failure()
          run: |
            echo "::group::GitHub Issue Auto-Creation"
            python3 scripts/create_regression_issue.py load-test-results/regression-analysis.md || echo "::notice::Could not create issue (requires token in CI)"
            echo "::endgroup::"

        - name: Collect load test results
          if: always()
          run: |
            mkdir -p load-test-results
            echo "Load testing completed at $(date)" > load-test-results/summary.txt

        - name: Upload load test results
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: load-test-results
            path: load-test-results/
            retention-days: 30

        - name: Show logs on failure
          if: failure()
          run: |
            echo "::group::Service Logs"
            docker compose -f docker/compose.p2.cpu.yml logs
            echo "::endgroup::"

        - name: Teardown
          if: always()
          run: |
            docker compose -f docker/compose.p2.cpu.yml down -v

    build-check:
      name: Docker Build Check
      runs-on: ubuntu-latest
      needs: [lint, unit-tests]
      strategy:
        fail-fast: false
        matrix:
          service: [embedding, rag, mcp-server]

      steps:
        - uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build Docker image (dry-run)
          working-directory: services/${{ matrix.service }}
          run: |
            if [ -f Dockerfile ]; then
              docker build --no-cache -t ${{ matrix.service }}:ci-test .
              echo "::notice::✅ Docker build successful for ${{ matrix.service }}"
            else
              echo "::warning::No Dockerfile found for ${{ matrix.service }}"
            fi

    summary:
      name: CI Summary
      runs-on: ubuntu-latest
      needs: [lint, security-scan, unit-tests, integration-tests, rag-integration-tests, e2e-tests, build-check]
      if: always()
      steps:
        - name: Check CI status
          run: |
            echo "::notice::CI Pipeline completed"
            echo "::group::Core Tests"
            echo "::notice::Lint: ${{ needs.lint.result }}"
            echo "::notice::Security: ${{ needs.security-scan.result }}"
            echo "::notice::Unit Tests: ${{ needs.unit-tests.result }}"
            echo "::notice::Integration Tests: ${{ needs.integration-tests.result }}"
            echo "::notice::Build: ${{ needs.build-check.result }}"
            echo "::endgroup::"

            echo "::group::Issue #24 Tests"
            echo "::notice::RAG Integration (Phase 1): ${{ needs.rag-integration-tests.result }}"
            echo "::notice::E2E Tests (Phase 2): ${{ needs.e2e-tests.result }}"
            echo "::endgroup::"

            if [[ "${{ needs.lint.result }}" == "failure" ]] || \
               [[ "${{ needs.unit-tests.result }}" == "failure" ]] || \
               [[ "${{ needs.integration-tests.result }}" == "failure" ]] || \
               [[ "${{ needs.rag-integration-tests.result }}" == "failure" ]] || \
               [[ "${{ needs.e2e-tests.result }}" == "failure" ]]; then
              echo "::error::CI failed - check logs above"
              exit 1
            fi
